### ISSUE TITLE
config.yml file not formatted properly

### ISSUE THREAD

**Issue by gadaxmagicgadax** [Cisco-AMP/amp4e_ldap_tool#2]
I've run the tool with the config file formatted as per the example in the readme but gives me the following when I run amp4e_ldap_tool amp -c:

Traceback (most recent call last):
	10: from /usr/local/bin/amp4e_ldap_tool:23:in `<main>'
	 9: from /usr/local/bin/amp4e_ldap_tool:23:in `load'
	 8: from /Library/Ruby/Gems/2.6.0/gems/amp4e_ldap_tool-0.0.4/exe/amp4e_ldap_tool:5:in `<top (required)>'
	 7: from /Library/Ruby/Gems/2.6.0/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
	 6: from /Library/Ruby/Gems/2.6.0/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
	 5: from /Library/Ruby/Gems/2.6.0/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
	 4: from /Library/Ruby/Gems/2.6.0/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
	 3: from /Library/Ruby/Gems/2.6.0/gems/amp4e_ldap_tool-0.0.4/lib/amp4e_ldap_tool/cli.rb:24:in `amp'
	 2: from /Library/Ruby/Gems/2.6.0/gems/amp4e_ldap_tool-0.0.4/lib/amp4e_ldap_tool/cli.rb:24:in `new'
	 1: from /Library/Ruby/Gems/2.6.0/gems/amp4e_ldap_tool-0.0.4/lib/amp4e_ldap_tool/cisco_amp.rb:18:in `initialize'
/Library/Ruby/Gems/2.6.0/gems/amp4e_ldap_tool-0.0.4/lib/amp4e_ldap_tool/cisco_amp.rb:139:in `confirm_config': {:msg=>"The AMP section of the configuration file is not formatted properly"} (Amp4eLdapTool::AMPConfigError)

that's my config.yml:

#config.yml
:ldap:
  :host: srv-dc04.teleconsys.local
  :domain: teleconsys.local
  :credentials:
    :un: amm_gadaleta
    :pw: <password>
  :schema:
    :filter: "Laptop-Area Tecnica"
:amp:
  :host: https://api.eu.amp.cisco.com
  :api:
    :third_party:
    :key:	<the key>
    :version: "v1"

please advice
txs
ciao
Giovanni

**Comment by gadaxmagicgadax** [comment]
solved ! there was a tab in the file and the syntax was wrong
